#!/usr/bin/env python3
import argparse
import os
import glob
import subprocess
import datetime
import shutil
import sys

# Configuration
HISTORY_DIR = ".contexter_history"
SMART_UPDATE_SCRIPT = "smart_update.py"

def ensure_history_dir():
    if not os.path.exists(HISTORY_DIR):
        os.makedirs(HISTORY_DIR)
        # Create a README inside to explain what this is
        with open(os.path.join(HISTORY_DIR, "README.txt"), "w") as f:
            f.write("This directory contains patch files generated by context_tracker.py.\n")
            f.write("Each file represents a 'commit' of the project state.\n")

def run_command(cmd):
    """Run a shell command and return output."""
    try:
        result = subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"❌ Error running command: {cmd}")
        print(e.stderr)
        return None

def cmd_status():
    """Show pending changes (dry run of rsync)."""
    if not os.path.exists(".contexter_cache"):
        print("❓ No cache found. Run 'commit' to initialize the project baseline.")
        return

    # We reuse the logic from smart_update checks, or simpler: just check if smartupdate finds anything
    # But smartupdate updates cache on run, so we can't run it for status unless we add a --dry-run flag to it.
    # Since we can't easily modify smartupdate.py right now, we'll do a quick rsync check ourselves.
    
    print("🔍 Checking for changes...")
    # This mimics the smart_update detection logic
    rsync_cmd = "rsync -a -n -i --delete --exclude=.git --exclude=.contexter_cache --exclude=.contexter_history --exclude=__pycache__ ./ .contexter_cache/"
    output = run_command(rsync_cmd)
    
    if output:
        print("⚠️  Uncommitted changes detected:")
        for line in output.splitlines():
            # Parse rsync output for prettier display
            if line.startswith(">f") or line.startswith("hf"):
                parts = line.split(" ", 1)
                if len(parts) > 1:
                    print(f"  📝 Modified/New: {parts[1]}")
            elif line.startswith("*deleting"):
                parts = line.split(" ", 3)
                # "*deleting    path"
                print(f"  🗑️  Deleted: {line.split()[-1]}")
        print("\nUse 'commit <message>' to save these changes.")
    else:
        print("✨ Working directory is clean (synced with cache).")

def cmd_commit(message):
    """Run smartupdate and save the patch."""
    ensure_history_dir()
    
    # Sanitize message for filename
    safe_message = "".join([c if c.isalnum() or c in "-_" else "_" for c in message])
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{timestamp}_{safe_message}.md"
    patch_path = os.path.join(HISTORY_DIR, filename)
    
    print(f"🚀 Starting commit: '{message}'")
    
    # Determine command to run
    # Priority 1: Local 'smart_update.py' script (dev environment / source root)
    # Priority 2: Global 'smartupdate' command (installed)
    
    cmd_args = []
    if os.path.exists("smart_update.py"):
        cmd_args = ["python3", "smart_update.py", ".", patch_path]
    elif shutil.which("smartupdate"):
        cmd_args = ["smartupdate", ".", patch_path]
    else:
        print(f"❌ Error: 'smartupdate' command not found and 'smart_update.py' not in current directory.")
        print("   Please install the package or run from source root.")
        return

    # Run smartupdate
    try:
        env = os.environ.copy()
        env["PYTHONPATH"] = "." + os.pathsep + env.get("PYTHONPATH", "")
        result = subprocess.run(cmd_args, capture_output=True, text=True, check=True, env=env)
        output = result.stdout.strip()
    except subprocess.CalledProcessError as e:
        # Check if it was just "No changes" (smartupdate logic might exit differently or print to stdout)
        # Actually smartupdate returns 0 even if no changes, but prints message.
        # If it failed with non-zero, it's a real error.
        print(f"❌ Error running smartupdate: {e}")
        print(e.stderr)
        return

    # Check for specific output messages from smartupdate
    if "Project is already in sync" in output:
        print("⚠️  No changes to commit.")
        # Cleanup empty file if created
        if os.path.exists(patch_path) and os.path.getsize(patch_path) == 0:
            os.remove(patch_path)
        return

    if os.path.exists(patch_path):
        print(f"✅ Commit successful!")
        print(f"   💾 Saved patch: {patch_path}")
        print(f"   🔄 Cache updated to current state.")
    else:
        print("❌ Commit failed. No patch file was created.")
        if output:
            print(f"   Output: {output}")

def cmd_log():
    """List history."""
    ensure_history_dir()
    files = sorted(glob.glob(os.path.join(HISTORY_DIR, "*.md")), reverse=True)
    
    if not files:
        print("📭 No commits found.")
        return

    print("📜 Project History (Latest first):")
    print("-" * 50)
    for i, filepath in enumerate(files):
        filename = os.path.basename(filepath)
        # format: YYYYMMDD_HHMMSS_message.md
        try:
            parts = filename.split("_", 2)
            date_str = f"{parts[0]} {parts[1][:2]}:{parts[1][2:]}"
            msg = parts[2].rsplit(".", 1)[0].replace("_", " ")
            print(f"[{i}] {date_str} - {msg}")
            print(f"    ID: {filename}")
        except:
            print(f"[{i}] {filename}")
    print("-" * 50)

def cmd_show(commit_id):
    """Show the content of a patch."""
    # commit_id can be index or filename
    files = sorted(glob.glob(os.path.join(HISTORY_DIR, "*.md")), reverse=True)
    
    target_file = None
    
    # Try as index
    if commit_id.isdigit():
        idx = int(commit_id)
        if 0 <= idx < len(files):
            target_file = files[idx]
    
    # Try as filename match
    if not target_file:
        for f in files:
            if commit_id in os.path.basename(f):
                target_file = f
                break
    
    if target_file:
        print(f"🔎 Viewing Patch: {os.path.basename(target_file)}")
        print("=" * 50)
        with open(target_file, 'r') as f:
            print(f.read())
        print("=" * 50)
    else:
        print(f"❌ Commit '{commit_id}' not found.")

def cmd_revert(commit_id):
    """Revert changes from a specific patch."""
    # Find the patch file
    files = sorted(glob.glob(os.path.join(HISTORY_DIR, "*.md")), reverse=True)
    target_file = None
    
    if commit_id.isdigit():
        idx = int(commit_id)
        if 0 <= idx < len(files):
            target_file = files[idx]
    
    if not target_file:
        for f in files:
            if commit_id in os.path.basename(f):
                target_file = f
                break
    
    if not target_file:
        print(f"❌ Commit '{commit_id}' not found.")
        return

    print(f"Rx Reverting patch: {os.path.basename(target_file)}")
    
    # Check for 'patch' command
    if not shutil.which("patch"):
        print("❌ Error: 'patch' command not found. Cannot revert.")
        return

    # Parse the markdown patch and apply reversely
    import re
    diff_header_pattern = re.compile(r"^--- DIFF FOR: (.*) ---$")
    
    with open(target_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Split content by diff blocks
    # Logic: smartupdate writes "--- DIFF FOR: path ---\n\n```diff\n...content...\n```\n\n"
    # We regex for the blocks
    
    blocks = content.split("--- DIFF FOR: ")
    success_count = 0
    fail_count = 0
    
    for block in blocks:
        if not block.strip(): continue
        
        # Extract filename and content
        try:
            line1_end = block.find(" ---")
            filename = block[:line1_end].strip()
            
            # Find code block
            start = block.find("```diff")
            if start == -1: continue
            start += 7 # len("```diff")
            end = block.find("```", start)
            if end == -1: continue
            
            diff_content = block[start:end]
            if not diff_content.endswith("\n"): diff_content += "\n"
            
            print(f"  - Reverting {filename}...")
            
            # Run patch command
            # -R: Reverse
            # -p0: Strip 0 path components
            # --ignore-whitespace: Lenient
            process = subprocess.Popen(
                ["patch", "-R", "-p0", "--no-backup-if-mismatch", "--ignore-whitespace"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
            stdout, stderr = process.communicate(input=diff_content)
            
            if process.returncode == 0:
                success_count += 1
                print(f"    ✅ Reverted {filename}")
            else:
                print(f"    ❌ Failed: {stderr.strip() or stdout.strip()}")
                fail_count += 1
                
        except Exception as e:
            print(f"    ❌ Error processing block: {e}")
            fail_count += 1

    print(f"\nRevert complete. {success_count} files reverted, {fail_count} failed.")
    if success_count > 0:
        print("⚠️  Note: You may need to run 'commit' to save this reverted state if you want it in history.")

def main():
    parser = argparse.ArgumentParser(description="Lightweight version control wrapper for Contexter smartupdate.")
    subparsers = parser.add_subparsers(dest="command", help="Command to run")

    # Status
    subparsers.add_parser("status", help="Show pending changes")

    # Commit
    commit_parser = subparsers.add_parser("commit", help="Save changes as a patch")
    commit_parser.add_argument("message", help="Commit message")

    # Log
    subparsers.add_parser("log", help="Show commit history")
    subparsers.add_parser("history", help="Alias for log")

    # Show
    show_parser = subparsers.add_parser("show", help="View a patch file")
    show_parser.add_argument("commit_id", help="Commit index (from log) or partial filename")

    # Revert
    revert_parser = subparsers.add_parser("revert", help="Revert changes from a patch")
    revert_parser.add_argument("commit_id", help="Commit index or filename to revert")

    args = parser.parse_args()

    if args.command == "status":
        cmd_status()
    elif args.command == "commit":
        cmd_commit(args.message)
    elif args.command in ["log", "history"]:
        cmd_log()
    elif args.command == "show":
        cmd_show(args.commit_id)
    elif args.command == "revert":
        cmd_revert(args.commit_id)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
